// data.js

// Logged-in User Profile
export const userProfile = {
  id: 1,
  name: "Abhigyan Goswami",
  username: "abhigyan",
  avatar: "🧑‍💻",
  bio: "Full Stack Developer | Next.js | AI Enthusiast 🚀",
  stats: {
    posts: 25,
    followers: 1200,
    following: 310,
  },
};

// Suggestions List (Who to Follow)
export const suggestions = [
  {
    id: 1,
    username: "rohit_dev",
    avatar: "👨‍💻",
    description: "Frontend Developer",
  },
  {
    id: 2,
    username: "priya_codes",
    avatar: "👩‍💻",
    description: "MERN Stack Developer",
  },
  {
    id: 3,
    username: "ai_guru",
    avatar: "🤖",
    description: "AI & ML Enthusiast",
  },
  {
    id: 4,
    username: "travel_vibes",
    avatar: "🌍",
    description: "Traveler & Blogger",
  },
  {
    id: 5,
    username: "movie_buff",
    avatar: "🎬",
    description: "Movies & Reviews",
  },
];

// Feed Posts
export const initialPosts = [
  {
    id: 1,
    username: "abhigyan",
    name: "Abhigyan Goswami",
    avatar: "🧑‍💻",
    time: "2h",
    category: "Tech",
    content: "Just started building my Social Media App using Next.js 🔥",
    likes: 45,
    comments: 12,
    shares: 5,
    liked: false,
  },
  {
    id: 2,
    username: "rohit_dev",
    name: "Rohit Sharma",
    avatar: "👨‍💻",
    time: "5h",
    category: "Tech",
    content: "Tailwind CSS makes UI design so smooth 😍 Building UI today!",
    likes: 120,
    comments: 30,
    shares: 18,
    liked: false,
  },
  {
    id: 3,
    username: "sports_fan",
    name: "Virat Kohli",
    avatar: "🏏",
    time: "8h",
    category: "Sports",
    content: "Cricket match today was insane 🔥 What a finish!",
    likes: 400,
    comments: 85,
    shares: 60,
    liked: false,
  },
  {
    id: 4,
    username: "movie_buff",
    name: "Movie Buff",
    avatar: "🎬",
    time: "1d",
    category: "Movies",
    content: "Watched Interstellar again 🌌 Still the best sci-fi movie ever!",
    likes: 350,
    comments: 70,
    shares: 45,
    liked: false,
  },
  {
    id: 5,
    username: "travel_vibes",
    name: "Travel Vibes",
    avatar: "🌍",
    time: "2d",
    category: "Travel",
    content: "Goa trip was amazing 🌊✨ Beaches + sunset vibes = perfect!",
    likes: 500,
    comments: 150,
    shares: 90,
    liked: false,
  },
  {
    id: 6,
    username: "gamer_zone",
    name: "Gamer Zone",
    avatar: "🎮",
    time: "2d",
    category: "Gaming",
    content: "Just reached Diamond rank 🏆🔥 Gaming grind never stops!",
    likes: 280,
    comments: 60,
    shares: 25,
    liked: false,
  },
  {
    id: 7,
    username: "music_love",
    name: "Music Lover",
    avatar: "🎶",
    time: "3d",
    category: "Music",
    content: "Listening to Arijit Singh on loop 🎧✨ Best vibes ever!",
    likes: 310,
    comments: 95,
    shares: 40,
    liked: false,
  },
  {
    id: 8,
    username: "priya_codes",
    name: "Priya Verma",
    avatar: "👩‍💻",
    time: "4d",
    category: "Tech",
    content: "Next.js App Router is really powerful. SSR + API routes 💯",
    likes: 210,
    comments: 55,
    shares: 40,
    liked: false,
  },
  {
    id: 9,
    username: "football_king",
    name: "Cristiano Ronaldo",
    avatar: "⚽",
    time: "5d",
    category: "Sports",
    content: "Football training session today 💪🔥 Discipline is everything.",
    likes: 600,
    comments: 140,
    shares: 100,
    liked: false,
  },
  {
    id: 10,
    username: "cinema_world",
    name: "Cinema World",
    avatar: "🍿",
    time: "6d",
    category: "Movies",
    content: "Marvel movies are getting crazier every year 😭🔥",
    likes: 450,
    comments: 120,
    shares: 75,
    liked: false,
  },
];

// Notifications Data (For Notifications Page)
export const notificationsData = [
  {
    id: 1,
    type: "like",
    user: "rohit_dev",
    avatar: "👨‍💻",
    message: "liked your post",
    time: "2m",
    read: false,
  },
  {
    id: 2,
    type: "follow",
    user: "priya_codes",
    avatar: "👩‍💻",
    message: "started following you",
    time: "10m",
    read: false,
  },
  {
    id: 3,
    type: "comment",
    user: "ai_guru",
    avatar: "🤖",
    message: "commented: Nice🔥",
    time: "1h",
    read: false,
  },
  {
    id: 4,
    type: "like",
    user: "travel_vibes",
    avatar: "🌍",
    message: "liked your post",
    time: "3h",
    read: true,
  },
  {
    id: 5,
    type: "comment",
    user: "movie_buff",
    avatar: "🎬",
    message: "commented: Amazing content 🎥🔥",
    time: "1d",
    read: true,
  },
];
